export { default as TagsInput } from './Tagsinput.vue'
export { default as TagsInputInput } from './TagsInputinput.vue'
export { default as TagsInputItem } from './tags-input-item.vue'
export { default as TagsInputItemDelete } from './tags-input-item-delete.vue'
export { default as TagsInputItemText } from './tags-input-item-text.vue'
